export const LOG_REDACTION_PATHS = [
  "password",
  "newPassword",
  "currentPassword",
  "accessToken",
  "refreshToken",
  "access_token",
  "refresh_token",
  "authorization",
  "cookie",
  "set-cookie",
  "set_cookie",
  "supabaseAnonKey",
  "supabaseServiceRoleKey",
  "serviceRoleKey",
  "clientIpHashKey",
  "nested.password",
  "nested.access_token",
  "nested.refresh_token",
  "nested.authorization",
  "nested.cookie",
  "nested.set_cookie",
  "nested.supabaseUrl",
  "nested.anonKey",
  "nested.hashKey",
  "nested.deeply.password",
  "supabaseUrl",
  "anonKey",
  "hashKey",

  "req.headers.authorization",
  "req.headers.cookie",
  "req.headers.set-cookie",
  "request.headers.authorization",
  "request.headers.cookie",
  "res.headers.set-cookie",
  "response.headers.set-cookie",

  "headers.authorization",
  "headers.cookie",
  "headers.set-cookie",

  // P3.7 — Idempotency redaction: raw keys, tokens, and hashes must never appear in logs
  "headers.idempotency-key",
  "req.headers.idempotency-key",
  "idempotencyKey",
  "rawKey",
  "leaseToken",
  "requestHash",
];
