export const ERROR_CODES = {
  // Authentication Errors
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  INVALID_AUTHORIZATION_HEADER: "INVALID_AUTHORIZATION_HEADER",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  INVALID_AUTHENTICATION_CLAIMS: "INVALID_AUTHENTICATION_CLAIMS",
  AUTHENTICATION_SERVICE_UNAVAILABLE: "AUTHENTICATION_SERVICE_UNAVAILABLE",

  // Core Application Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  INVALID_JSON: "INVALID_JSON",
  CORS_ORIGIN_DENIED: "CORS_ORIGIN_DENIED",
  CSRF_ORIGIN_DENIED: "CSRF_ORIGIN_DENIED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
