export const ERROR_CODES = {
  // Authentication Errors
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  INVALID_AUTHORIZATION_HEADER: "INVALID_AUTHORIZATION_HEADER",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  INVALID_AUTHENTICATION_CLAIMS: "INVALID_AUTHENTICATION_CLAIMS",
  AUTHENTICATION_SERVICE_UNAVAILABLE: "AUTHENTICATION_SERVICE_UNAVAILABLE",
  INVALID_AUTH_REQUEST: "INVALID_AUTH_REQUEST",
  INVALID_LOGIN_CREDENTIALS: "INVALID_LOGIN_CREDENTIALS",
  REFRESH_SESSION_REQUIRED: "REFRESH_SESSION_REQUIRED",
  INVALID_REFRESH_SESSION: "INVALID_REFRESH_SESSION",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  REGISTRATION_UNAVAILABLE: "REGISTRATION_UNAVAILABLE",
  AUTHENTICATION_RATE_LIMIT_EXCEEDED: "AUTHENTICATION_RATE_LIMIT_EXCEEDED",

  // Core Application Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  USER_PROFILE_NOT_FOUND: "USER_PROFILE_NOT_FOUND",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  INVALID_JSON: "INVALID_JSON",
  MALFORMED_JSON: "MALFORMED_JSON",
  UNSUPPORTED_CONTENT_ENCODING: "UNSUPPORTED_CONTENT_ENCODING",
  URI_TOO_LONG: "URI_TOO_LONG",
  TOO_MANY_QUERY_PARAMETERS: "TOO_MANY_QUERY_PARAMETERS",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  CORS_ORIGIN_DENIED: "CORS_ORIGIN_DENIED",
  CSRF_ORIGIN_DENIED: "CSRF_ORIGIN_DENIED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
