import { randomUUID } from "node:crypto";
import { loadApplicationConfig } from "../../src/config/app-config.js";
import { createPrivilegedSupabaseClient } from "../../src/integrations/supabase/admin/create-privileged-supabase-client.js";
import express from "express";
import { createHttpServer } from "../../src/server/create-http-server.js";
import { bootstrapObservability } from "../../src/observability/index.js";
import { createSafeConfigSummary } from "../../src/config/index.js";
import { createApp } from "../../src/app.js";
import * as dotenv from "dotenv";
import { join } from "node:path";

// 1. Force dotenv to load .env.test (which is generated by `supabase status -o env > .env.test`)
// We use process.cwd() because tests are run from the project root.
const envResult = dotenv.config({ path: join(process.cwd(), ".env.test") });

if (envResult.error) {
  console.warn(
    "Failed to load .env.test. Tests may fail if local credentials are not otherwise present in the environment.",
  );
}

const parsedLocalEnv = envResult.parsed || {};

if (Object.keys(parsedLocalEnv).length === 0) {
  throw new Error(
    "CRITICAL: .env.test file is empty or missing. Run: npx supabase status -o env > .env.test",
  );
}

// Map Supabase CLI standard variable names to our app config schema variables
const mappedEnv = {
  ...process.env,
  ...parsedLocalEnv,
  ...(parsedLocalEnv.API_URL ? { SUPABASE_URL: parsedLocalEnv.API_URL } : {}),
  ...(parsedLocalEnv.ANON_KEY ? { SUPABASE_PUBLISHABLE_KEY: parsedLocalEnv.ANON_KEY } : {}),
  ...(parsedLocalEnv.SERVICE_ROLE_KEY
    ? { SUPABASE_SERVICE_ROLE_KEY: parsedLocalEnv.SERVICE_ROLE_KEY }
    : {}),
};

// Load valid configuration globally for tests
export const appConfig = loadApplicationConfig({
  source: mappedEnv,
});

// Ensure this file is never executed against a non-local or unknown environment
if (!("url" in appConfig.supabase) || !appConfig.supabase.url.includes("127.0.0.1:54321")) {
  throw new Error(
    "SECURITY FAULT: Real environment tests must only run against local Supabase (127.0.0.1:54321)",
  );
}

// Ensure privileged key exists for admin operations in tests
if (!("privilegedKey" in appConfig.supabase) || !appConfig.supabase.privilegedKey) {
  throw new Error(
    "SECURITY FAULT: Real environment tests require a privileged service_role key to manage test data.",
  );
}

/**
 * Creates an entire Express application and Server bound for tests
 */
export function createTestApp(overrideConfig = appConfig) {
  const configSummary = createSafeConfigSummary(overrideConfig);
  const tempApp = express();
  const server = createHttpServer(tempApp, overrideConfig);
  const observability = bootstrapObservability({ config: overrideConfig, server });

  const app = createApp({ config: overrideConfig, observability, configSummary });

  server.removeAllListeners("request");
  server.on("request", app);

  // Mark app as ready for health endpoints
  observability.lifecycle.markReady();

  return { app, server, observability };
}

/**
 * A privileged client strictly for setting up and tearing down test data.
 */
export const testAdminClient = createPrivilegedSupabaseClient({
  config: appConfig,
});

/**
 * Helper to generate deterministic test identities.
 * Uses a unique suffix per test run to prevent collisions during parallel execution.
 */
export function generateTestIdentity(prefix: string) {
  const uniqueId = randomUUID();
  return {
    email: `${prefix}-${uniqueId}@example.test`,
    password: `TestPassword!${uniqueId}`, // Strong test-only password
    uniqueId,
  };
}

/**
 * Deletes a user deterministically from auth.users (which cascades to public.users via DB relations or can be left to the cascade).
 */
export async function cleanupTestUser(userId: string) {
  if (!userId) return;

  // First, explicitly delete dependent rows that might cause foreign key locking/AuthRetryableFetchError
  try {
    await testAdminClient
      .from("interview_session_questions")
      .delete()
      .eq("session_id", "ignored")
      .neq("id", "00000000-0000-0000-0000-000000000000"); // Broad delete isn't easy here, let's just delete interviews which cascade
    await testAdminClient.from("interviews").delete().eq("user_id", userId);
    await testAdminClient.from("users").delete().eq("id", userId);
  } catch (e) {
    console.warn(`Failed to cleanup public.users or dependents for ${userId}`, e);
  }

  let retries = 2;
  while (retries >= 0) {
    const { error } = await testAdminClient.auth.admin.deleteUser(userId);
    if (!error) return;

    if (retries === 0) {
      console.warn(
        `[BEST EFFORT] Failed to cleanup test user ${userId}: Auth deletion failed after retries`,
      );
      return;
    }

    console.warn(`Retryable Auth user cleanup failure for ${userId}, retrying in 500ms...`);
    await new Promise((resolve) => setTimeout(resolve, 500));
    retries--;
  }
}
